@component('mail::message')

<h1 class="medium">Konfirmasi </h1>

Hai {{ $name }}, your registration is almost complete. Please click the link below to activate your account.

After that use the password below to log in to Goalkes Mitra account.

@component('mail::panel')
Your password: ```{{ $password }}```
@endcomponent


@component('mail::button', ['url' => $url, 'color' => 'green'])
Activate Account
@endcomponent

Regards,<br>
Goalkes Team

@component('mail::subcopy')
*This email automatically generated by system, please don't reply this email*
@endcomponent

@endcomponent
